import { chromium } from 'playwright';
const url = process.argv[2] || 'http://localhost:5173/?d3';
const out = process.argv[3] || '/tmp/hero.png';
const browser = await chromium.launch({ headless: false, args: ['--no-sandbox'] });
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 2, colorScheme: 'dark' });
const page = await ctx.newPage();
const errors = [];
page.on('console', m => { if (m.type() === 'error') errors.push(m.text()); });
page.on('pageerror', e => errors.push('PAGEERROR: ' + e.message));
await page.goto(url, { waitUntil: 'networkidle', timeout: 30000 });
await page.mouse.move(1080, 430);
await page.waitForTimeout(4500);
await page.screenshot({ path: out });
console.log('SAVED', out, 'ERRORS', JSON.stringify(errors.slice(0,8)));
await browser.close();
